export enum KEYS_QUERY {
  GET_ALL_PRODUCT = "GET_ALL_PRODUCT",
  GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID",
  GET_ALL_PRODUCT_REVIEW = "GET_ALL_PRODUCT_REVIEW",
  GET_ALL_INTERIOR_PRODUCT = "GET_ALL_INTERIOR_PRODUCT",
}
